/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#f790e0',
        'on-tertiary': '#6c1561',
        'surface-container-low': '#131313',
        surface: '#0e0e0e',
        'primary-fixed-dim': '#2be800',
        background: '#0e0e0e',
        'on-secondary-container': '#f9f6ff',
        'on-secondary-fixed': '#002691',
        'on-tertiary-fixed': '#380033',
        'surface-container-high': '#201f1f',
        'surface-container-highest': '#262626',
        'on-tertiary-fixed-variant': '#6a1460',
        secondary: '#8197ff',
        'on-primary-container': '#0b5800',
        'primary-fixed': '#2ff801',
        'inverse-surface': '#fcf8f8',
        'tertiary-fixed-dim': '#e883d2',
        'on-primary-fixed': '#064200',
        'on-error': '#490013',
        'secondary-fixed': '#c7cfff',
        'error-container': '#a70138',
        'error-dim': '#d73357',
        'tertiary-fixed': '#f790e0',
        'primary-dim': '#2be800',
        'on-background': '#ffffff',
        'on-primary': '#0d6100',
        'surface-bright': '#2c2c2c',
        'surface-container': '#1a1919',
        'on-surface-variant': '#adaaaa',
        'secondary-fixed-dim': '#b5c0ff',
        'on-tertiary-container': '#5f0656',
        'on-primary-fixed-variant': '#0d6200',
        primary: '#8eff71',
        'on-secondary': '#001661',
        'surface-container-lowest': '#000000',
        'surface-variant': '#262626',
        outline: '#777575',
        'secondary-dim': '#3e65ff',
        'tertiary-dim': '#e883d2',
        'inverse-on-surface': '#565554',
        'inverse-primary': '#106f00',
        'outline-variant': '#494847',
        'on-surface': '#ffffff',
        tertiary: '#ffa3e9',
        error: '#ff6e84',
        'on-error-container': '#ffb2b9',
        'secondary-container': '#124af0',
        'on-secondary-fixed-variant': '#003cd6',
        'surface-dim': '#0e0e0e',
        'surface-tint': '#8eff71',
        'primary-container': '#2ff801',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
}
