name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.release.outputs.published }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: release
        run: |
          npx semantic-release > result.log || exit_code=$?
          cat result.log
          grep -q "Published release" result.log && echo "published=true" >> $GITHUB_OUTPUT || echo "published=false" >> $GITHUB_OUTPUT
          exit ${exit_code:-0}

      - name: Build site
        if: ${{ steps.release.outputs.published == 'true' }}
        run: npm run build

      - name: Upload GitHub Pages artifact
        if: ${{ steps.release.outputs.published == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
    
  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.published == 'true'
    environment: 
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4