name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'   # Can deploy only the code in the main branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for a new tag
        id: check-tag
        run: |
          if [ -z "$(git tag --contains HEAD)" ]; then
            echo "No new tag. Skipping deployment."
            echo "published=false" >> $GITHUB_OUTPUT
          else
            echo "New tag detected. Proceeding with deployment."
            echo "published=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy to GH Pages
        if: ${{ steps.check-tag.outputs.published == 'true' }}
        run: |
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm run build
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}